paths:
  raw: data/raw
  processed: data/processed

data:
  climate_file: monthly_climate.csv      
  soil_file: soil_data.csv               
  merge_keys: ["LAT", "LON"]
  output_file: dataset.csv

validate:
  required_climate_cols: ["LAT", "LON"]
  required_soil_cols: ["LAT", "LON"]